version: '3.8'

services:
  my_bot:
    build: .
    container_name: tywin
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
